### ISSUE TITLE
issues upgrading to 2.2.1 

### ISSUE THREAD

**Issue by ppastur** [vigonotion/hass-simpleicons#257]
Hi,
Ive enjoyed the use of simpleicons for several years now. Recently I upgraded from 2.1.0 and found that it causes and error in HA (2023.7.3 Container).  

**Troubleshooting tried**

- tried to reload HA integration (failed)
- tried to delete simpleicon HA integration (failed)
- checked resource is correct and still present
- I rolled back to 2.2.0 (still failed)
- I rolled back to 2.1.0 (worked)

**Here is the error message in the log**

```
Logger: homeassistant.setup
Source: custom_components/simpleicons/__init__.py:5
Integration: Simple Icons ([documentation](https://github.com/vigonotion/hass-simpleicons))
First occurred: 16:23:12 (1 occurrences)
Last logged: 16:23:12

Setup failed for custom integration simpleicons: Unable to import component: cannot import name 'StaticPathConfig' from 'homeassistant.components.http' (/lsiopy/lib/python3.11/site-packages/homeassistant/components/http/__init__.py)
Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/simpleicons/__init__.py", line 5, in <module>
    from homeassistant.components.http import StaticPathConfig
ImportError: cannot import name 'StaticPathConfig' from 'homeassistant.components.http' (/lsiopy/lib/python3.11/site-packages/homeassistant/components/http/__init__.py)
```

Have I missed something basic or is this a result of being on an older version of HA?

Thank you in advance for your time to look at this.

**Comment by ppastur** [comment]
The issue was due to my version of HomeAssistant.  I upgraded to the latest and that has resolved the issue
