### ISSUE TITLE
Unable to update to version 2.3.0

### ISSUE THREAD

**Issue by etricky** [vigonotion/hass-simpleicons#260]
I'm unable to update from version 2.2.1 to the latest 2.3.0 release. Looking at the logs, it complains that the file hass-simpleicons.zip is missing and indeed this release does not include it. @vigonotion can you please check? Thank you!

HA Logs
```
2024-11-18 23:40:24.275 INFO (MainThread) [custom_components.hacs] Starting download, v2.3.0
2024-11-18 23:40:24.284 INFO (MainThread) [custom_components.hacs] <Integration vigonotion/hass-simpleicons> Running pre installation steps
2024-11-18 23:40:24.284 INFO (MainThread) [custom_components.hacs] <Integration vigonotion/hass-simpleicons> Pre installation steps completed
2024-11-18 23:40:24.286 INFO (MainThread) [custom_components.hacs] <Integration vigonotion/hass-simpleicons> Running installation steps
2024-11-18 23:40:27.099 ERROR (MainThread) [custom_components.hacs] Download failed - Got status code 404 when trying to download https://github.com/vigonotion/hass-simpleicons/releases/download/v2.3.0/hass-simpleicons.zip
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 709, in async_download_file
    raise HacsException(
custom_components.hacs.exceptions.HacsException: Got status code 404 when trying to download https://github.com/vigonotion/hass-simpleicons/releases/download/v2.3.0/hass-simpleicons.zip
2024-11-18 23:40:27.116 ERROR (MainThread) [custom_components.hacs] <Integration vigonotion/hass-simpleicons> Failed to download https://github.com/vigonotion/hass-simpleicons/releases/download/tags/v2.3.0/hass-simpleicons.zip
2024-11-18 23:40:27.140 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547656952000] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/hacs/repositories/base.py", line 1436, in async_download_repository
    await self.async_install(version=ref)
  File "/config/custom_components/hacs/repositories/base.py", line 884, in async_install
    await self.async_install_repository(version=version)
  File "/config/custom_components/hacs/repositories/base.py", line 986, in async_install_repository
    raise HacsException("Could not download, see log for details")
custom_components.hacs.exceptions.HacsException: Could not download, see log for details

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/hacs/update.py", line 88, in async_install
    await self.repository.async_download_repository(ref=version or self.latest_version)
  File "/config/custom_components/hacs/repositories/base.py", line 1438, in async_download_repository
    raise HacsException(
custom_components.hacs.exceptions.HacsException: Downloading vigonotion/hass-simpleicons with version v2.3.0 failed with (Could not download, see log for details)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2763, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2806, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 999, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1071, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 154, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 458, in async_install_with_progress
    await self.async_install(version, backup)
  File "/config/custom_components/hacs/update.py", line 90, in async_install
    raise HomeAssistantError(exception) from exception
homeassistant.exceptions.HomeAssistantError: Downloading vigonotion/hass-simpleicons with version v2.3.0 failed with (Could not download, see log for details)
```

**Comment by beecho01** [comment]
I am also getting the following:

```
homeassistant.exceptions.HomeAssistantError: Downloading vigonotion/hass-simpleicons with version v2.3.0 failed with (Could not download, see log for details)
```

With debugger enabled:

```
2024-11-19 00:26:55.087 ERROR (MainThread) [custom_components.hacs] Download failed - Got status code 404 when trying to download https://github.com/vigonotion/hass-simpleicons/releases/download/v2.3.0/hass-simpleicons.zip
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 709, in async_download_file
    raise HacsException(
custom_components.hacs.exceptions.HacsException: Got status code 404 when trying to download https://github.com/vigonotion/hass-simpleicons/releases/download/v2.3.0/hass-simpleicons.zip
2024-11-19 00:26:55.090 ERROR (MainThread) [custom_components.hacs] <Integration vigonotion/hass-simpleicons> Failed to download https://github.com/vigonotion/hass-simpleicons/releases/download/tags/v2.3.0/hass-simpleicons.zip
2024-11-19 00:26:55.114 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547154796192] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/hacs/repositories/base.py", line 1436, in async_download_repository
    await self.async_install(version=ref)
  File "/config/custom_components/hacs/repositories/base.py", line 884, in async_install
    await self.async_install_repository(version=version)
  File "/config/custom_components/hacs/repositories/base.py", line 986, in async_install_repository
    raise HacsException("Could not download, see log for details")
custom_components.hacs.exceptions.HacsException: Could not download, see log for details
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/config/custom_components/hacs/update.py", line 88, in async_install
    await self.repository.async_download_repository(ref=version or self.latest_version)
  File "/config/custom_components/hacs/repositories/base.py", line 1438, in async_download_repository
    raise HacsException(
custom_components.hacs.exceptions.HacsException: Downloading vigonotion/hass-simpleicons with version v2.3.0 failed with (Could not download, see log for details)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 157, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 502, in async_install_with_progress
    await self.async_install(version, backup)
  File "/config/custom_components/hacs/update.py", line 90, in async_install
    raise HomeAssistantError(exception) from exception
homeassistant.exceptions.HomeAssistantError: Downloading vigonotion/hass-simpleicons with version v2.3.0 failed with (Could not download, see log for details)
```

**Comment by sheminasalam** [comment]
HASS is looking for a zip file to download but the release only has source code. This is the issue. I hope soon they would add the zip file to the release.

**Comment by Victorsueca** [comment]
It seems like the action that was meant to pack and upload the zip file has failed. 
The "Set version number" step is still trying to run update_manifest.py, but this file was removed in 0904e22

**Comment by fuxing-at** [comment]
Yes. The Release-ZIP is missing

![image](https://github.com/user-attachments/assets/2fca68fc-5a05-4fb5-a18a-0fbccd67be5f)

**Comment by broyuken** [comment]
replying same here isn't going to do anything but fill up peoples inboxes. Just click subscribe on the right side of this issue and you can see any useful status updates.
