### ISSUE TITLE
Invalid handler specified

### ISSUE THREAD

**Issue by Vebryn** [vigonotion/hass-simpleicons#265]
Hi,

This integration is really usefull, I like it !

I notice it doesn't work anymore with latest HASS version (2023.12.4). I redownload through HACS then when I add it I get:

> Config flow could not be loaded: {"message":"Invalid handler specified"}

Using configuration.yml, I get:

> Component error: simpleicons - No module named 'simplepycons'

Trace logs:

```
Setup failed for custom integration 'simpleicons': Unable to import component: No module named 'simplepycons'

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1034, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1014, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/simpleicons/__init__.py", line 6, in <module>
    from simplepycons import all_icons
ModuleNotFoundError: No module named 'simplepycons'
```

Any idea ?

Best regards.

**Comment by Vebryn** [comment]
I'm using container image docker.io/homeassistant/home-assistant:stable

**Comment by Vebryn** [comment]
Solved, I did add/remove again then remove/add icon. Don't understand, whenever, so great that it work's !
